name: Install Dependencies
description: Use node and install the project dependencies
inputs:
  NPM_TOKEN:
    required: true
    description: 'Auth token for npm'
  debug:
    required: true
    description: 'Just to test things'

runs:
  using: 'composite'
  steps:
    - name: ⎔ Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'yarn'
    - name: Debugging
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: |
        echo "Here is the debug variable: $DEBUG"
        echo "And here is the npm token: $NPM_TOKEN"
    - name: 📥 Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
      env:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        debug: ${{ inputs.debug }}